# Generated by Django 5.0.2 on 2024-03-01 13:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTaxPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeTaxDeductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_tax_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payperiod')),
            ],
        ),
    ]
