# Generated by Django 5.0.2 on 2024-02-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
