# Generated by Django 5.0.2 on 2024-02-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingallowance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalallowance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mobileallowance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='otherallowance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='travelallowance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='uniformallowance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, unique=True),
        ),
    ]
