# Generated by Django 5.0.2 on 2024-02-27 16:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance', '0003_mobileallowancepayments'),
        ('employee', '0005_alter_employee_other_deductions'),
        ('payroll', '0009_rename_employee_total_deductions_payroll_employee_total_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowancePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_allowance_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('travel_allowance_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('housing_allowance_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('medical_allowance_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('uniform_allowance_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('other_allowance_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_allowance_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payperiod')),
            ],
        ),
        migrations.DeleteModel(
            name='MobileAllowancePayments',
        ),
    ]
