# Generated by Django 5.0.2 on 2024-02-27 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance', '0004_allowancepayments_delete_mobileallowancepayments'),
        ('employee', '0005_alter_employee_other_deductions'),
        ('payroll', '0009_rename_employee_total_deductions_payroll_employee_total_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancepayments',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='allowancepayments',
            name='pay_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payperiod'),
        ),
    ]
