# Generated by Django 5.0.2 on 2024-02-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance', '0005_alter_allowancepayments_employee_and_more'),
        ('payroll', '0009_rename_employee_total_deductions_payroll_employee_total_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancepayments',
            name='pay_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.payperiod'),
        ),
    ]
