# Generated by Django 5.0.2 on 2024-02-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='other_deductions',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Other deductions'),
        ),
    ]
