# Generated by Django 5.0.2 on 2024-03-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='userprofile',
        ),
    ]
