# Generated by Django 5.0.2 on 2024-03-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_certification_degree_employmenttype_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='degrees',
        ),
        migrations.AddField(
            model_name='employee',
            name='degrees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.degree'),
        ),
    ]
