# Generated by Django 5.0.2 on 2024-03-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_userprofile_employee_alter_userprofile_user'),
        ('employee', '0004_remove_employee_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='accounts.userprofile'),
        ),
    ]
