# Generated by Django 5.0.2 on 2024-03-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_degrees_employee_degrees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='degrees',
            new_name='degree',
        ),
    ]
