# Generated by Django 5.0.2 on 2024-02-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deductions', '0001_initial'),
        ('employee', '0004_alter_employee_other_deductions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='other_deductions',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='deductions.deductions'),
        ),
    ]
