# Generated by Django 5.0.2 on 2024-03-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_rename_degrees_employee_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='certifications',
        ),
        migrations.AddField(
            model_name='employee',
            name='certifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.certification'),
        ),
    ]
