# Generated by Django 5.0.2 on 2024-02-27 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance', '0005_alter_allowancepayments_employee_and_more'),
        ('core', '0002_initial'),
        ('deductions', '0001_initial'),
        ('employee', '0005_alter_employee_other_deductions'),
        ('payroll', '0009_rename_employee_total_deductions_payroll_employee_total_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='housing_allowance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='allowance.housingallowance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jobtitle'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='medical_allowance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='allowance.medicalallowance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_allowance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='allowance.mobileallowance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_allowance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='allowance.otherallowance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_deductions',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='deductions.deductions'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_payroll', to='payroll.payroll'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.section'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='travel_allowance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='allowance.travelallowance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uniform_allowance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='allowance.uniformallowance'),
        ),
    ]
