# Generated by Django 5.0.2 on 2024-03-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_user'),
        ('employee', '0005_employee_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='accounts.userprofile'),
        ),
    ]
