# Generated by Django 5.0.2 on 2024-03-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_certifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='certifications',
            new_name='certification',
        ),
    ]
