# Generated by Django 5.0.2 on 2024-02-29 07:59

import django.db.models.deletion
import employee.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance', '0006_alter_allowancepayments_pay_period'),
        ('core', '0005_alter_jobtitle_name'),
        ('deductions', '0001_initial'),
        ('employee', '0007_employee_created_by_employee_edited_by'),
        ('payroll', '0010_alter_payperiod_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('employee_id', models.BigIntegerField(blank=True, db_index=True, default=None, verbose_name='Employee ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='First name')),
                ('second_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Second name')),
                ('last_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Last name')),
                ('date_of_birth', models.DateField(default=None, verbose_name='Date of birth')),
                ('nationality', models.CharField(blank=True, choices=[('Jordan', 'Jordan'), ('USA', 'United States'), ('UK', 'United Kingdom')], default=None, max_length=25, null=True, verbose_name='Nationality')),
                ('national_id_number', models.IntegerField(blank=True, null=True, verbose_name='National ID Number')),
                ('id_expiry_date', models.DateField(default=None, verbose_name='ID Expiry Date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1, verbose_name='Gender')),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], default='', max_length=1, verbose_name='Marital status')),
                ('phone_number', models.CharField(max_length=18, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('emergency_contact_name', models.CharField(blank=True, default=None, max_length=100, verbose_name='Emergency contact name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=18, null=True, verbose_name='Emergency contact phone')),
                ('number_of_dependents', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of dependents')),
                ('employment_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'Contract'), ('INT', 'Intern'), ('OTH', 'Other')], max_length=3, null=True, verbose_name='Employment Type')),
                ('is_department_head', models.BooleanField(default=False, verbose_name='Is Department Head')),
                ('hire_date', models.DateField(default=None, verbose_name='Hire date')),
                ('contract_expiry_date', models.DateField(blank=True, default=None, null=True, verbose_name='Contract Expiry Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('degrees', models.CharField(blank=True, choices=[('HS', 'High school'), ('AD', 'Associate / Diploma'), ('BA', 'Bachelor'), ('MA', 'Master'), ('PHD', 'Doctorate (Ph.D.)')], max_length=3, null=True, verbose_name='Degrees')),
                ('certifications', models.CharField(default=None, max_length=100, verbose_name='Certifications')),
                ('social_security_number', models.IntegerField(verbose_name='Social security number')),
                ('tax_identification_number', models.IntegerField(blank=True, null=True, verbose_name='Tax identification number')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank name')),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank branch')),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank account number')),
                ('basic_salary', models.PositiveIntegerField(default=0, verbose_name='Basic salary')),
                ('image', models.TextField(blank=True, default='default.jpg', max_length=100, null=True, validators=[employee.models.validate_image_size], verbose_name='Image')),
                ('copy_of_id_card', models.TextField(blank=True, max_length=100, null=True, validators=[employee.models.validate_file_size, employee.models.validate_file_extension], verbose_name='Copy of ID card')),
                ('copy_of_passport', models.TextField(blank=True, max_length=100, null=True, validators=[employee.models.validate_file_size, employee.models.validate_file_extension], verbose_name='Copy of passport')),
                ('copy_of_degree', models.TextField(blank=True, max_length=100, null=True, validators=[employee.models.validate_file_size, employee.models.validate_file_extension], verbose_name='Copy of degree')),
                ('copy_of_visas', models.TextField(blank=True, max_length=100, null=True, validators=[employee.models.validate_file_size, employee.models.validate_file_extension], verbose_name='Copy of visas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.department')),
                ('edited_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('housing_allowance', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allowance.housingallowance')),
                ('job_title', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.jobtitle')),
                ('medical_allowance', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allowance.medicalallowance')),
                ('mobile_allowance', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allowance.mobileallowance')),
                ('other_allowance', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allowance.otherallowance')),
                ('other_deductions', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deductions.deductions')),
                ('payroll', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.payroll')),
                ('section', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.section')),
                ('travel_allowance', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allowance.travelallowance')),
                ('uniform_allowance', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='allowance.uniformallowance')),
            ],
            options={
                'verbose_name': 'historical Employee',
                'verbose_name_plural': 'historical Employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
