# Generated by Django 5.0.2 on 2024-02-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_historicalemployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='edited_by',
        ),
    ]
