# Generated by Django 5.0.2 on 2024-02-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employeehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeehistory',
            name='history_change_summary',
        ),
    ]
