# Generated by Django 5.0.2 on 2024-02-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_employeehistory_history_change_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeHistory',
        ),
    ]
