# Generated by Django 5.0.2 on 2024-02-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_delete_employeehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalEmployee',
        ),
    ]
