# Generated by Django 5.0.2 on 2024-03-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='employee',
        ),
    ]
