# Generated by Django 5.0.2 on 2024-03-03 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_employee'),
        ('employee', '0004_remove_employee_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
