# Generated by Django 5.0.2 on 2024-02-27 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=2)),
                ('year', models.IntegerField(default=2024)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('allowance', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('rate_allowance', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('total_allowance', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('employee_ss_deduction', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('company_ss_deduction', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('income_tax_deduction', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payroll', to='employee.employee')),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payperiod')),
            ],
        ),
    ]
