# Generated by Django 5.0.2 on 2024-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='allowance',
            new_name='medical_allowance',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='rate_allowance',
            new_name='mobile_allowance',
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='travel_allowance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='uniform_allowance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
