# Generated by Django 5.0.2 on 2024-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_rename_allowance_payroll_medical_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
