# Generated by Django 5.0.2 on 2024-02-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_payroll_company_ss_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
