# Generated by Django 5.0.2 on 2024-02-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payroll_other_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='employee_total_deduction',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
