# Generated by Django 5.0.2 on 2024-02-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payroll_employee_total_deduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='employee_total_deduction',
            new_name='employee_total_deductions',
        ),
    ]
