# Generated by Django 5.0.2 on 2024-02-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_rename_employee_total_deduction_payroll_employee_total_deductions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='employee_total_deductions',
            new_name='employee_total_deduction',
        ),
    ]
