# Generated by Django 5.0.2 on 2024-02-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_rename_employee_total_deductions_payroll_employee_total_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payperiod',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='February', max_length=20),
        ),
    ]
